apiVersion: v1
kind: Secret
metadata:
  name: {{ include "astra.fullname" . }}-secret
  labels:
    {{- include "astra.labels" . | nindent 4 }}
type: Opaque
data:
  GROQ_API_KEY: {{ .Values.secrets.groqApiKey | b64enc | quote }}
  ASTRA_API_KEY: {{ .Values.secrets.astraApiKey | b64enc | quote }}
  {{- if .Values.secrets.slackBotToken }}
  SLACK_BOT_TOKEN: {{ .Values.secrets.slackBotToken | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.slackChannelId }}
  SLACK_CHANNEL_ID: {{ .Values.secrets.slackChannelId | b64enc | quote }}
  {{- end }}
