"""
Astra — Application Entry Point

Run the server:
    uvicorn app.main:app --reload           # development
    uvicorn app.main:app --host 0.0.0.0    # production

Interactive API docs (auto-generated by FastAPI):
    http://localhost:8000/docs    (Swagger UI)
    http://localhost:8000/redoc   (ReDoc)

Prometheus metrics:
    http://localhost:8000/metrics
"""

from contextlib import asynccontextmanager
from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse

from app.core.config import settings
from app.core.logging import configure_logging, logger
from app.db.database import initialise_database
from app.api.routes import router as api_router
from app.api.metrics import metrics_app
from app.api.schemas import HealthResponse


# ── Lifespan ────────────────────────────────────────────────────────────────────
# This replaces the deprecated @app.on_event("startup") / ("shutdown") pattern.
# Everything before `yield` runs at startup; everything after `yield` at shutdown.

@asynccontextmanager
async def lifespan(app: FastAPI):
    # Startup
    configure_logging()
    logger.info("Astra AIOps Agent starting up.", extra={"version": "0.4.0"})

    initialise_database(settings.audit_db_path)
    logger.info("Audit database ready.", extra={"path": settings.audit_db_path})

    yield

    # Shutdown
    logger.info("Astra AIOps Agent shutting down.")


# ── Application ────────────────────────────────────────────────────────────────

app = FastAPI(
    title="Astra AIOps Agent",
    description=(
        "Enterprise-grade self-healing Kubernetes agent. "
        "Astra investigates alerts, plans remediations, and either "
        "executes fixes automatically or requests human approval via Slack."
    ),
    version="0.4.0",
    lifespan=lifespan,
    docs_url="/docs",
    redoc_url="/redoc",
)


# ── Global Error Handler ───────────────────────────────────────────────────────
# Catches any unhandled exception in any route and returns a clean 500 response.
# The full exception is logged server-side; the caller only sees a safe message.

@app.exception_handler(Exception)
async def global_exception_handler(request: Request, exc: Exception) -> JSONResponse:
    logger.error(
        "Unhandled exception",
        extra={"path": str(request.url), "error": str(exc)},
        exc_info=exc,
    )
    return JSONResponse(
        status_code=500,
        content={"error": "An internal error occurred. Check the server logs for details."},
    )


# ── Routes ──────────────────────────────────────────────────────────────────────

app.include_router(api_router)                  # /webhook, /alertmanager, /threads, /history
app.mount("/metrics", metrics_app)              # Prometheus scrape endpoint


@app.get("/health", response_model=HealthResponse, tags=["system"])
def health_check() -> HealthResponse:
    """Returns 200 OK when the server is running. Used by load balancers and monitoring."""
    return HealthResponse()
