"""
Astra — Application Entry Point

Run the server:
    uvicorn app.main:app --reload           # development
    uvicorn app.main:app --host 0.0.0.0    # production

Interactive API docs (auto-generated by FastAPI):
    http://localhost:8000/docs    (Swagger UI)
    http://localhost:8000/redoc   (ReDoc)

Prometheus metrics:
    http://localhost:8000/metrics
"""

from contextlib import asynccontextmanager
from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse

from app.core.config import settings
from app.core.logging import configure_logging, logger
from app.db.database import initialise_database
from app.api.routes import router as api_router
from app.api.metrics import metrics_app
from app.api.schemas import HealthResponse


# ── Lifespan ────────────────────────────────────────────────────────────────────
# This replaces the deprecated @app.on_event("startup") / ("shutdown") pattern.
# Everything before `yield` runs at startup; everything after `yield` at shutdown.

@asynccontextmanager
async def lifespan(app: FastAPI):
    # Startup
    configure_logging()
    logger.info("Astra AIOps Agent starting up.", extra={"version": "0.4.0"})

    initialise_database(settings.audit_db_path)
    logger.info("Audit database ready.", extra={"path": settings.audit_db_path})

    yield

    # Shutdown
    logger.info("Astra AIOps Agent shutting down.")


# ── Application ────────────────────────────────────────────────────────────────

app = FastAPI(
    title="Astra AIOps Agent",
    description=(
        "Enterprise-grade self-healing Kubernetes agent. "
        "Astra investigates alerts, plans remediations, and either "
        "executes fixes automatically or requests human approval via Slack."
    ),
    version="0.4.0",
    lifespan=lifespan,
    docs_url="/docs",
    redoc_url="/redoc",
)


# ── Global Error Handler ───────────────────────────────────────────────────────
# Catches any unhandled exception in any route and returns a clean 500 response.
# The full exception is logged server-side; the caller only sees a safe message.

@app.exception_handler(Exception)
async def global_exception_handler(request: Request, exc: Exception) -> JSONResponse:
    logger.error(
        "Unhandled exception",
        extra={"path": str(request.url), "error": str(exc)},
        exc_info=exc,
    )
    return JSONResponse(
        status_code=500,
        content={"error": "An internal error occurred. Check the server logs for details."},
    )


# ── Routes ──────────────────────────────────────────────────────────────────────

app.include_router(api_router)                  # /webhook, /alertmanager, /threads, /history
app.mount("/metrics", metrics_app)              # Prometheus scrape endpoint


@app.get("/health", tags=["system"], summary="Liveness probe — is Astra running?")
def health_check() -> dict:
    """
    Shallow liveness probe — returns 200 OK if the server process is alive.
    Used by Kubernetes liveness probes and load balancers.
    """
    return {"status": "healthy", "version": "0.4.0"}


@app.get("/health/ready", tags=["system"], summary="Readiness probe — are all dependencies ready?")
def readiness_check() -> JSONResponse:
    """
    Deep readiness probe — verifies all critical dependencies are operational.
    Returns 200 OK only if Astra can actually serve requests.
    Returns 503 Service Unavailable if any dependency is down.

    Used by Kubernetes readiness probes to stop routing traffic to a broken pod.
    Kubernetes will NOT send new requests to this pod while this returns 503.
    """
    import sqlite3
    checks   = {}
    healthy  = True

    # ── Check 1: Audit database is readable ─────────────────────────────────
    try:
        conn = sqlite3.connect(settings.audit_db_path, timeout=2)
        conn.execute("SELECT 1")
        conn.close()
        checks["audit_db"] = "ok"
    except Exception as exc:
        checks["audit_db"] = f"error: {exc}"
        healthy = False

    # ── Check 2: Checkpoint database is readable ────────────────────────────
    try:
        conn = sqlite3.connect("astra_checkpoints.db", timeout=2)
        conn.execute("SELECT 1")
        conn.close()
        checks["checkpoint_db"] = "ok"
    except Exception as exc:
        checks["checkpoint_db"] = f"error: {exc}"
        healthy = False

    # ── Check 3: LLM API reachable (lightweight HEAD request, no token cost) ────
    try:
        import httpx
        r = httpx.head("https://api.groq.com", timeout=3)
        checks["llm_api"] = "ok" if r.status_code < 500 else f"degraded: HTTP {r.status_code}"
    except Exception as exc:
        # LLM unreachable is degraded but not fatal — we have the fallback chain
        checks["llm_api"] = f"degraded: {exc}"
        # Do not mark healthy=False for LLM — let the retry/fallback handle it

    status_code = 200 if healthy else 503
    return JSONResponse(
        status_code=status_code,
        content={
            "status":  "ready" if healthy else "not_ready",
            "version": "0.4.0",
            "checks":  checks,
        },
    )
