alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname', 'pod', 'namespace']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'astra-aiops'
      routes:
      - matchers:
          - alertname = "KubePodCrashLooping"
        receiver: 'astra-aiops'
    receivers:
    - name: 'null'
    - name: 'astra-aiops'
      webhook_configs:
      - url: 'http://host.docker.internal:8081/alertmanager'
        send_resolved: true
        http_config:
          authorization:
            type: Bearer
            credentials: 'change-me-in-production'

defaultRules:
  create: true
  rules:
    kubePodCrashLooping: true
